package com.bytecode.luyuan.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val loginTitle: String,
    val usernameLabel: String,
    val passwordLabel: String,
    val loginButton: String,
    val sessionListTitle: String,
    val newChat: String,
    val settingsTitle: String,
    val generalGroup: String,
    val account: String,
    val accountSubtitle: String,
    val notifications: String,
    val darkMode: String,
    val language: String,
    val dataPrivacyGroup: String,
    val clearHistory: String,
    val clearHistorySubtitle: String,
    val aboutGroup: String,
    val version: String,
    val helpSupport: String,
    val logout: String,
    val guest: String,
    val notLoggedIn: String,
    val aiAssistant: String,
    val online: String,
    val typeMessage: String,
    val welcomeBack: String,
    val selectLanguage: String,
    val cancel: String
)

val EnglishStrings = AppStrings(
    loginTitle = "Welcome Back",
    usernameLabel = "Username",
    passwordLabel = "Password",
    loginButton = "Login",
    sessionListTitle = "AI Sessions",
    newChat = "New Chat",
    settingsTitle = "Settings",
    generalGroup = "General",
    account = "Account",
    accountSubtitle = "Manage your account",
    notifications = "Notifications",
    darkMode = "Dark Mode",
    language = "Language",
    dataPrivacyGroup = "Data & Privacy",
    clearHistory = "Clear History",
    clearHistorySubtitle = "Delete all chat history",
    aboutGroup = "About",
    version = "Version",
    helpSupport = "Help & Support",
    logout = "Logout",
    guest = "Guest",
    notLoggedIn = "Not logged in",
    aiAssistant = "AI Assistant",
    online = "Online",
    typeMessage = "Type a message...",
    welcomeBack = "Welcome Back",
    selectLanguage = "Select Language",
    cancel = "Cancel"
)

val ChineseStrings = AppStrings(
    loginTitle = "欢迎回来",
    usernameLabel = "用户名",
    passwordLabel = "密码",
    loginButton = "登录",
    sessionListTitle = "历史会话",
    newChat = "新会话",
    settingsTitle = "设置",
    generalGroup = "通用",
    account = "账号管理",
    accountSubtitle = "管理您的账号信息",
    notifications = "通知",
    darkMode = "深色模式",
    language = "语言",
    dataPrivacyGroup = "数据与隐私",
    clearHistory = "清除历史记录",
    clearHistorySubtitle = "删除所有聊天记录",
    aboutGroup = "关于",
    version = "版本",
    helpSupport = "帮助与支持",
    logout = "退出登录",
    guest = "游客",
    notLoggedIn = "未登录",
    aiAssistant = "AI 助手",
    online = "在线",
    typeMessage = "输入消息...",
    welcomeBack = "欢迎回来",
    selectLanguage = "选择语言",
    cancel = "取消"
)

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }
